name: Build

env:
  ProjectName: Steam++

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        configuration: [Debug, Release]
        os: [ windows-latest ]
      # os: [ windows-latest, macOS-latest, ubuntu-latest ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Install macOS SDK(macOS)
      if: matrix.os == 'macOS-latest'
      run: sudo dotnet workload install macos
      
    - name: Install macOS SDK(Windows)
      if: matrix.os == 'windows-latest'
      run: dotnet workload install macos

    - name: Install Maui(Windows)
      if: matrix.os == 'windows-latest'
      run: dotnet workload install maui

    - name: Verify dotnet info
      run: dotnet --info

    - name: Checkout Credentials repository
      uses: actions/checkout@v2
      with:
        repository: SteamTools-Team/Credentials
        token: ${{ secrets.REPO_TOKEN }}
        path: ./Credentials

    - name: Copy pfx and snk To Source
      run: |
        copy ".\Credentials\*.pfx" .
        copy ".\Credentials\*.snk" .
        dir *.pfx -s

    - name: dotnet restore SteamToolsV2+.sln
      if: matrix.os == 'windows-latest'
      run: dotnet restore ./SteamToolsV2+.sln
      
    - name: dotnet restore SteamToolsV2+.Linux.sln
      if: matrix.os == 'ubuntu-latest'
      run: dotnet restore ./SteamToolsV2+.Linux.slnf
      
    - name: dotnet restore SteamToolsV2+.Mac.sln
      if: matrix.os == 'macOS-latest'
      run: dotnet restore ./SteamToolsV2+.Mac.slnf
      
    - name: Build AvaloniaApp ${{ matrix.configuration }}
      run: dotnet build ./src/ST.Client.Desktop.Avalonia.App/ST.Client.Avalonia.App.csproj -c "${{ matrix.configuration }}"
      
    - name: Run CommonUnit
      run: dotnet test ./tests/Common.UnitTest/Common.UnitTest.csproj -c "${{ matrix.configuration }}"

    - name: Run ST.Client.UnitTest
      run: dotnet test ./tests/ST.Client.UnitTest/ST.Client.UnitTest.csproj -c "${{ matrix.configuration }}"

    - name: Run ST.Client.Desktop.UnitTest
      run: dotnet test ./tests/ST.Client.Desktop.UnitTest/ST.Client.Desktop.UnitTest.csproj -c "${{ matrix.configuration }}"

#    - name: dotnet ST.Client.Desktop.UnitTest test
#      if: matrix.os != 'windows-latest'
#      run: dotnet test ./tests/ST.Client.Desktop.UnitTest/ST.Client.Desktop.UnitTest.csproj

    - name: Build ${{ env.Configuration }} & Package All
      if: ${{ matrix.os == 'windows-latest' && !startsWith(github.ref, 'refs/tags/') }}
      shell: pwsh
      run: .\packaging\build.ps1 -configuration ${{ env.Configuration }}

    - name: Upload fd-win-x64 App ${{ env.Configuration }}
      continue-on-error: true
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.ProjectName }}_fd_win_x64_${{ env.Configuration }}
        path: src\ST.Client.Desktop.Avalonia.App\bin\${env:Configuration}\Publish\FrameworkDependent\win-x64\

    - name: Upload win-x64 App ${{ env.Configuration }}
      continue-on-error: true
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.ProjectName }}_win_x64_${{ env.Configuration }}
        path: src\ST.Client.Desktop.Avalonia.App\bin\${env:Configuration}\Publish\win-x64\

    - name: Upload osx-x64 App ${{ env.Configuration }}
      continue-on-error: true
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.ProjectName }}_osx_x64_${{ env.Configuration }}
        path: src\ST.Client.Desktop.Avalonia.App\bin\${env:Configuration}\Publish\osx-x64\

    - name: Upload linux-x64 App ${{ env.Configuration }}
      continue-on-error: true
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.ProjectName }}_linux_x64_${{ env.Configuration }}
        path: src\ST.Client.Desktop.Avalonia.App\bin\${env:Configuration}\Publish\linux-x64\

    - name: Upload linux-arm64 App ${{ env.Configuration }}
      continue-on-error: true
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.ProjectName }}_linux_arm64_${{ env.Configuration }}
        path: src\ST.Client.Desktop.Avalonia.App\bin\${env:Configuration}\Publish\linux-arm64\
