name: .NET

on:
  push:
    branches: [ master,develop ]
  pull_request:
    branches: [ master,develop ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: dotnet info
      run: dotnet --info
    - name: dotnet restore
      run: dotnet restore ./SteamToolsV2+.sln
    - name: dotnet CommonUnit build
      run: dotnet build ./test/Common.UnitTest/Common.UnitTest.csproj
    - name: dotnet CommonUnit test
      run: dotnet test ./test/Common.UnitTest/Common.UnitTest.csproj
    - name: dotnet Common.UnitTest.Droid build
      run: dotnet build ./test/Common.UnitTest.Droid/Common.UnitTest.Droid.csproj
    - name: dotnet Common.UnitTest.Droid test
      run: dotnet test ./test/Common.UnitTest.Droid/Common.UnitTest.Droid.csproj
    - name: dotnet Common.UnitTest.Droid.App build
      run: dotnet build ./test/Common.UnitTest.Droid.App/Common.UnitTest.Droid.App.csproj
    - name: dotnet Common.UnitTest.Droid.App test
      run: dotnet test ./test/Common.UnitTest.Droid.App/Common.UnitTest.Droid.App.csproj
    - name: dotnet ST.Client.UnitTest build
      run: dotnet build ./test/ST.Client.UnitTest/ST.Client.UnitTest.csproj
    - name: dotnet ST.Client.UnitTest test
      run: dotnet test ./test/ST.Client.UnitTest/ST.Client.UnitTest.csproj
